### ISSUE TITLE
Save bookmark race condition

### ISSUE THREAD

**Issue by crazy-man** [msimerson/safe-log-reader#17]
Hello,
I use safe-log-reader as a part of log-ship-elastic-postfix.
After running it on production server, I've noticed missing data in elasticsearch.
After a small investigation with DEBUG=1, it was clear that safe-log-reader skips lines of mail.log
Race condition was discovered in function batchSaveDone (index.js line 134):
 slr.bookmark.save(slr.filePath, slr.lines.position, function (err) {

Function  Bookmark.prototype.save (bookmark.js line 41):

calls   fs.stat(logFilePath, function (err, stat) {

There is some time passes between function call and fs.stat. 

During that period mail.log is updated with new lines(in the background), by the time fs.stat is called, stat.size is bigger than expected. 

On the next iteration reading is resumed from the wrong position.

Ideally it would be better after reading a line to save current file offset using something like "tell".
And advance it on each readLine().

**Comment by msimerson** [comment]
Hi @crazy-man, I have a few things:
1. Do you see any 'lines@EOF' errors being emitted in your stderr?
2. PR #18 is a band-aid for the race condition, at the expense of a little bit of CPU.
3. I'm not familiar with "tell" that would be able to save the current file offset. I'm not even sure how that could work. Please do tell.
4. Since I'm using a node.js transform stream, I generally am unable to determine what the current file offset is for any given EOL. There may be an exception to that. Depending on how the file is being written, it may be that every time I get an EOF, it will coincide with an EOL. If that's the case, then this.liner.bytes would contain the correct log file offset. I have assembled PR #19 based on this premise. Would you mind testing?

**Comment by crazy-man** [comment]
Hello Matt,
1. I don't see  'lines@EOF' errors in stderr
2. I expected that nodejs would have tell, like python, here's an example:
   http://www.tutorialspoint.com/python/file_tell.htm
   seems like not.
   I would use if after each read call (similar to fs.stat.size, but without race condition).
3. I tested PR #19, seems like it doesn't work.
   Here's a part of the log:
   [2016-09-18 13:23:04.471] bookmark.save: line: 123
   [2016-09-18 13:23:04.523] watcher saw change on mail.log
   [2016-09-18 13:23:14.541] bookmark.read: line 123
   [2016-09-18 13:23:14.541]   lines.start: 123
   [2016-09-18 13:23:14.542]   bytes.start: 10704
   [2016-09-18 13:23:14.542] opening for read: /var/log/mail.log
   [2016-09-18 13:23:14.542] PARSE ERROR for syslog:ostfix mail system is not running

bytes.start: 10704 does not reflect actual position at line 123( Which is 13709).
On the next iteration file is just opened at position 10704(which is in the middle of line 90):
"Sep 14 12:45:59 debian8 postfix/postfix-script[12932]: fatal: the Postfix mail system is not running"
and threw parse error.

Since this bug is critical for us(and runs in production), I made some hot-fix patch, that solves the issue:

[hotfix.txt](https://github.com/DoubleCheck/safe-log-reader/files/478716/hotfix.txt)

I just added bytesOffset member to slr, and on each readLine, I advance it by size of the line ( + length of EOL character) that we read. 
In this case nothing is missed, and on the next iteration we proceed from the last position.
I'm not sure if that's the right place for that(maybe it should be placed in line-splitter.js or somewhere else), but seems like it works. You can use it for comparing results with your solution.

Good luck,
Constantine

**Comment by msimerson** [comment]
> I'm not sure if that's the right place for that(maybe it should be placed in line-splitter.js or somewhere else), but seems like it works. 

Having given it some time to reflect, I think right where you put it is the best. Thanks for the contribution!  I have applied your hotfix and just released 1.0.6.
