### ISSUE TITLE
any way to make it watch forever ? 

### ISSUE THREAD

**Issue by jodevsa** [msimerson/safe-log-reader#22]
Hello,

Is there anyway where i could make it watch the file "forever"
even when end of file happens ?

**Comment by msimerson** [comment]
It already does. That's one of the built in features.

**Comment by jodevsa** [comment]
Clearly i'm missing the idea, could you kindly provide an example , of like continuously reading a .log file ? "forever", 
what i understood is this does only read until "lines read are equal to batch size " ?

**Comment by msimerson** [comment]
[test/reader.js](https://github.com/msimerson/safe-log-reader/blob/master/test/reader.js#L101-L263)
